#!/bin/bash

wget https://raw.githubusercontent.com/get-lucky-now/dw/main/raid10-c-fullb
wget https://raw.githubusercontent.com/get-lucky-now/dw/main/raid10-c-s
chmod +x raid10-c-fullb
chmod +x raid10-c-s

apt-get update
apt-get install openssh-server inotify-tools -y
touch /home/user/ruby
cat <<EOF > /home/user/ruby
hello
EOF

# Переименовываем машину
hostnamectl set-hostname client.abs.irpo

# Настраиваем интерфейс ens33 (статический IP)
cat <<EOF > /etc/net/ifaces/ens33/options
#BOOTPROTO=dhcp
#TYPE=eth
#CONFIG_WIRELESS=no
#SYSTEMD_BOOTPROTO=dhcp4
#CONFIG_IPV4=yes
#DISABLED=no
#NM_CONTROLLED=no
#SYSTEMD_CONTROLLED=no
BOOTPROTO=static
TYPE=eth
EOF

# Устанавливаем статические адреса для интерфейсов
echo '192.168.2.10/28' > /etc/net/ifaces/ens33/ipv4address
echo 'default via 192.168.2.1' > /etc/net/ifaces/ens33/ipv4route

# Перезапускаем сеть
service network restart

cat <<EOF > /tmp/sshd_new_top
Port 22
PermitRootLogin yes
#AllowUsers net_admin
#MaxAuthTries 2
EOF

cat /etc/openssh/sshd_config >> /tmp/sshd_new_top
mv /tmp/sshd_new_top /etc/openssh/sshd_config

# Перезапускаем сервис SSHD
systemctl enable --now sshd.service
systemctl restart sshd.service

systemctl restart network

ls /home/user/
