#!/bin/bash

# Переименовываем машину
hostnamectl set-hostname client.abs.irpo

# Настраиваем интерфейс ens33 (статический IP)
cat <<EOF > /etc/net/ifaces/ens33/options
BOOTPROTO=static
TYPE=eth
EOF

# Устанавливаем статические адреса для интерфейсов
echo '192.168.2.10/28' > /etc/net/ifaces/ens33/ipv4address
echo 'default via 192.168.2.1' > /etc/net/ifaces/ens33/ipv4route

# Перезапускаем сеть
service network restart
