#!/bin/bash

# === raid-server-backup-setup.sh ===
# Назначение: Настройка RAID 10 и подготовка структуры для резервного копирования с клиентских машин
# Используется: rsync по SSH, безопасный доступ, без экспорта NFS
# Требуется: mdadm, rsync, openssh-server

# Проверка дисков
lsblk
read -p "Нажми Enter, чтобы продолжить..."

# Создание RAID10 массива
mdadm --create /dev/md0 --level=10 --raid-devices=4 /dev/sd[b-e]
#mdadm --create /dev/md0 --level=10 --raid-devices=4 /dev/sd[c-f]

# Просмотр состояния RAID массива
cat /proc/mdstat
read -p "Нажми Enter, чтобы продолжить..."

# Сохранение информации о массиве
mdadm --detail -scan > /etc/mdadm.conf

# Форматирование раздела
#fdisk /dev/md0 <<< "$(printf '%s\n' n p 1 2048  w)"

echo ">>> Форматирование RAID-массива в ext4"
#mkfs.ext4 /dev/md0p1
mkfs.ext4 /dev/md0

echo ">>> Создание точек монтирования и структуры каталогов для резервного копирования"
mkdir -p /raid10
mkdir -p /raid10/backup/client-linux
mkdir -p /raid10/backup/client-win
mkdir -p /raid10/versions/client-linux
mkdir -p /raid10/versions/client-win

echo ">>> Добавление RAID-массива в /etc/fstab и монтирование"
echo '/dev/md0p1  /raid10  ext4  defaults  0  0' >> /etc/fstab
read -p "Нажми Enter, чтобы продолжить..."

