#!/bin/bash

mount -a

echo ">>> Создание точек монтирования и структуры каталогов для резервного копирования"
mkdir -p /raid10/backup/client-linux
mkdir -p /raid10/backup/client-win
mkdir -p /raid10/versions/client-linux
mkdir -p /raid10/versions/client-win

groupadd backup
usermod -aG backup user
chown -R root:backup /raid10/backup/client-linux
chmod -R 770 /raid10/backup/client-linux

echo ">>> Установка rsync и SSH-сервера для безопасной передачи данных"
#apt update
#apt install -y rsync openssh-server

echo ">>> Включение и запуск SSH-сервиса"
systemctl enable --now ssh

echo ">>> Установка прав доступа"
chown -R root:backup /raid10
chmod -R 750 /raid10
chmod -R 770 /raid10/backup
chmod -R 770 /raid10/versions

usermod -aG backup user

chown -R root:backup /raid10/backup
chmod -R 770 /raid10/backup

echo ">>> Сервер RAID готов для приёма резервных копий от клиентов (rsync по SSH)."
echo "Каталоги:"
echo "  /raid10/backup/client-linux"
echo "  /raid10/backup/client-win"
echo "  /raid10/versions/client-linux"
echo "  /raid10/versions/client-win"
