#!/bin/bash

# Переименовываем машину
hostnamectl set-hostname backup-server.abs.irpo

# Настраиваем интерфейс ens33 (статический IP)
cat <<EOF > /etc/net/ifaces/ens33/options
#BOOTPROTO=dhcp
#TYPE=eth
#CONFIG_WIRELESS=no
#SYSTEMD_BOOTPROTO=dhcp4
#CONFIG_IPV4=yes
#DISABLED=no
#NM_CONTROLLED=no
#SYSTEMD_CONTROLLED=no
BOOTPROTO=static
TYPE=eth
EOF

# Устанавливаем статические адреса для интерфейсов
echo '192.168.1.10/26' > /etc/net/ifaces/ens33/ipv4address
echo 'default via 192.168.1.1' > /etc/net/ifaces/ens33/ipv4route

# Перезапускаем сеть
service network restart
