#!/bin/bash

# Переименовываем машину
hostnamectl set-hostname backup-server.abs.irpo

# Настраиваем интерфейс ens19 (статический IP)
cat <<EOF > /etc/net/ifaces/ens19/options
BOOTPROTO=static
TYPE=eth
EOF

# Устанавливаем статические адреса для интерфейсов
echo '192.168.1.10/26' > /etc/net/ifaces/ens19/ipv4address
echo 'default via 192.168.1.1' > /etc/net/ifaces/ens19/ipv4route

# Перезапускаем сеть
service network restart
