#!/bin/bash

wget https://raw.githubusercontent.com/get-lucky-now/dw/main/raid10-server-b1
wget https://raw.githubusercontent.com/get-lucky-now/dw/main/raid10-server-b2
chmod +x raid10-server-b1
chmod +x raid10-server-b2

# Переименовываем машину
hostnamectl set-hostname backup-server.abs.irpo

# Создаем нового пользователя
useradd user -u 1010
id user
echo " Напоминание: resu"
passwd user

# Настраиваем интерфейс ens33 (статический IP)
cat <<EOF > /etc/net/ifaces/ens33/options
#BOOTPROTO=dhcp
#TYPE=eth
#CONFIG_WIRELESS=no
#SYSTEMD_BOOTPROTO=dhcp4
#CONFIG_IPV4=yes
#DISABLED=no
#NM_CONTROLLED=no
#SYSTEMD_CONTROLLED=no
BOOTPROTO=static
TYPE=eth
EOF

# Устанавливаем статические адреса для интерфейсов
echo '192.168.1.10/26' > /etc/net/ifaces/ens33/ipv4address
echo 'default via 192.168.1.1' > /etc/net/ifaces/ens33/ipv4route

# Перезапускаем сеть
service network restart

cat <<EOF > /tmp/sshd_new_top
Port 22
PermitRootLogin yes
#AllowUsers net_admin
#MaxAuthTries 2
EOF

cat /etc/openssh/sshd_config >> /tmp/sshd_new_top
mv /tmp/sshd_new_top /etc/openssh/sshd_config

# Перезапускаем сервис SSHD
systemctl enable --now sshd.service
systemctl restart sshd.service

systemctl restart network
